version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ichgramm-backend
    restart: unless-stopped
    volumes:
      - ./backend/app:/app
      # - /app/node_modules
    ports:
      - '3001:80'
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ichgram-frontend
    restart: unless-stopped
    volumes:
      - ./frontend/app:/app
    ports:
      # TODO switch to 3000:80
      - '3000:3000'
      # - '8080:80'
    environment:
      # ВАЖНО: в React (CRA) переменные должны начинаться с REACT_APP_
      - REACT_APP_API_URL=http://ichgramm-backend:3001/api/v1
      - REACT_APP_SOCKET_URL=http://ichgramm-backend:3001
    depends_on:
      - backend
